# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

stages:
- stage:
  pool:
    FOR SONARQUBE
  jobs:
  - job: MavenBuild
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'Sonarqube testing'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=Employee_Registration_Employee_Registration_AYlIZ2dMnXsFX0hM52RE
    
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
        
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
        
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.war'
          TargetFolder: $(Build.ArtifactStagingDirectory)
    
    - upload: $(Build.ArtifactStagingDirectory)
      artifact: artifact
    
- stage:
  pool:
    emp
  jobs:
  - job: Deploy
    steps:
    - script:
        echo $(Build.ArtifactStagingDirectory)